sonar.projectKey=Amodamendis_Greenhouse-management-App-tier
sonar.organization=amodamendis

# Tells SonarCloud where your actual code is
sonar.sources=src

# Tells SonarCloud to ignore third-party libraries so it doesn't fail your scan
sonar.exclusions=**/node_modules/**, tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info



